# Public release: MOATTERS reproducibility code
# MOATTERS = Modularity, Observability, Auditability, and Traceability
# for Task-conditioned Evidence Reconstruction into Patient States.
# Generated from the locked analysis scripts; scientific logic was preserved.
# ============================================================
# MOATTERS Stage BP Module Rewiring V1
# Input : D:\MOATTERS-Output\MOATTERS_STAGE_BP_Attractor_Pilot_V3_20260530
# Output: D:\MOATTERS-Output\MOATTERS_STAGE_BP_Module_Rewiring_V1_20260531
#
# Purpose:
#   Analyze whether stage-associated high-D BP groups form
#   co-activity modules and whether these modules are rewired
#   between Stage I/II and Stage III/IV.
#
# Required input files per cancer folder from V3:
#   *_DStage_BP_results.csv
#   *_selected_BP_for_network.csv
#   *_BP_correlation_network_edges.csv
#   *_BP_correlation_network_node_metrics.csv
#   *_BP_network_summary.csv
#   *_selected_BP_gene_overlap.csv
#
# Outputs:
#   per cancer:
#     *_module_assignment.csv
#     *_module_summary.csv
#     *_module_rewiring_early_vs_late.csv
#     *_module_overlap_matrix.csv
#     *_module_graph_*.png
#     *_module_rewiring_summary.json
#
#   all cancer:
#     MOATTERS_module_rewiring_all_cancer_summary.csv
#     MOATTERS_module_summary_all_cancers.csv
#     MOATTERS_module_assignment_all_cancers.csv
#     MOATTERS_module_rewiring_pairs_all_cancers.csv
# ============================================================

import os
import re
import json
import math
import warnings
from pathlib import Path
from moatters.config import data_path, output_path
from collections import defaultdict, Counter

import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt


# ============================================================
# 0. PATH CONFIG
# ============================================================

TEMP_ROOT = output_path()

INPUT_DIR = TEMP_ROOT / "MOATTERS_STAGE_BP_Attractor_Pilot_V3_20260530"
OUT_DIR = TEMP_ROOT / "MOATTERS_STAGE_BP_Module_Rewiring_V1_20260531"
OUT_DIR.mkdir(parents=True, exist_ok=True)

print("Input:", INPUT_DIR)
print("Output:", OUT_DIR)


# ============================================================
# 1. USER CONFIG
# ============================================================

# Community detection method:
#   "greedy_modularity" is available in standard networkx.
COMMUNITY_METHOD = "greedy_modularity"

# Edge weight column from V3 network edge files.
EDGE_WEIGHT_COL = "abs_corr"

# If graph has no edges, every BP becomes its own singleton module.
SINGLETON_IF_NO_EDGES = True

# Redundancy warning thresholds.
MEAN_JACCARD_WARNING = 0.20
MAX_JACCARD_WARNING = 0.50
MEAN_OVERLAP_COEF_WARNING = 0.50

# For graph plotting
MAKE_FIGURES = True
MAX_LABEL_LEN = 28

# Groups generated by V3
NETWORK_GROUPS = ["all_patients", "stage_I_II", "stage_III_IV"]

# Stage names for rewiring
EARLY_GROUP = "stage_I_II"
LATE_GROUP = "stage_III_IV"


# ============================================================
# 2. BASIC HELPERS
# ============================================================

def extract_cancer_code_from_folder(folder_name):
    """
    V3 output folders are usually cancer codes: BRCA, BLCA, etc.
    """
    return str(folder_name)


def safe_read_csv(path):
    path = Path(path)
    if not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_csv(path, low_memory=False)
    except UnicodeDecodeError:
        return pd.read_csv(path, encoding="utf-8-sig", low_memory=False)
    except Exception as e:
        print(f"[WARN] Could not read {path}: {repr(e)}")
        return pd.DataFrame()


def safe_float(x, default=np.nan):
    try:
        if pd.isna(x):
            return default
        return float(x)
    except Exception:
        return default


def shorten_label(x, max_len=MAX_LABEL_LEN):
    s = str(x)
    if len(s) <= max_len:
        return s
    return s[:max_len - 3] + "..."


def infer_cancer_code_from_files(cancer_dir):
    """
    Try to infer code from file prefix if folder name is not enough.
    """
    files = list(Path(cancer_dir).glob("*_DStage_BP_results.csv"))
    if files:
        name = files[0].name
        return name.replace("_DStage_BP_results.csv", "")
    return Path(cancer_dir).name


def find_v3_cancer_dirs(input_dir):
    """
    Identify cancer subdirectories with V3 result files.
    """
    input_dir = Path(input_dir)
    dirs = []
    for p in input_dir.iterdir():
        if not p.is_dir():
            continue
        if list(p.glob("*_DStage_BP_results.csv")) and list(p.glob("*_BP_correlation_network_edges.csv")):
            dirs.append(p)
    return sorted(dirs)


# ============================================================
# 3. LOAD V3 FILES
# ============================================================

def load_v3_cancer_outputs(cancer_dir):
    cancer_dir = Path(cancer_dir)
    cancer_code = infer_cancer_code_from_files(cancer_dir)

    dstage_path = cancer_dir / f"{cancer_code}_DStage_BP_results.csv"
    selected_path = cancer_dir / f"{cancer_code}_selected_BP_for_network.csv"
    edges_path = cancer_dir / f"{cancer_code}_BP_correlation_network_edges.csv"
    metrics_path = cancer_dir / f"{cancer_code}_BP_correlation_network_node_metrics.csv"
    net_summary_path = cancer_dir / f"{cancer_code}_BP_network_summary.csv"
    gene_overlap_path = cancer_dir / f"{cancer_code}_selected_BP_gene_overlap.csv"

    dstage = safe_read_csv(dstage_path)
    selected = safe_read_csv(selected_path)
    edges = safe_read_csv(edges_path)
    node_metrics = safe_read_csv(metrics_path)
    net_summary = safe_read_csv(net_summary_path)
    gene_overlap = safe_read_csv(gene_overlap_path)

    return {
        "cancer_code": cancer_code,
        "dstage": dstage,
        "selected": selected,
        "edges": edges,
        "node_metrics": node_metrics,
        "net_summary": net_summary,
        "gene_overlap": gene_overlap,
        "paths": {
            "dstage": dstage_path,
            "selected": selected_path,
            "edges": edges_path,
            "node_metrics": metrics_path,
            "net_summary": net_summary_path,
            "gene_overlap": gene_overlap_path,
        }
    }


# ============================================================
# 4. GRAPH BUILDING
# ============================================================

def build_graph_for_group(edges_df, selected_terms, group_name):
    """
    Build BP correlation graph for a group.
    Nodes = selected BP terms.
    Edges = V3 correlation edges for that group.
    """
    G = nx.Graph()

    selected_terms = [str(x) for x in selected_terms if pd.notna(x)]
    G.add_nodes_from(selected_terms)

    if edges_df.empty:
        return G

    sub = edges_df[edges_df["group"].astype(str) == group_name].copy()

    if sub.empty:
        return G

    for _, r in sub.iterrows():
        a = str(r["bp1"])
        b = str(r["bp2"])

        if a not in G.nodes or b not in G.nodes:
            continue

        w = safe_float(r.get(EDGE_WEIGHT_COL, np.nan), default=np.nan)
        corr = safe_float(r.get("corr", np.nan), default=np.nan)
        p_corr = safe_float(r.get("p_corr", np.nan), default=np.nan)

        if pd.isna(w):
            w = abs(corr) if not pd.isna(corr) else 1.0

        G.add_edge(a, b, weight=w, corr=corr, p_corr=p_corr)

    return G


def detect_communities(G, method="greedy_modularity"):
    """
    Return dict node -> module_id and list of communities.
    """
    nodes = list(G.nodes())

    if len(nodes) == 0:
        return {}, []

    if G.number_of_edges() == 0:
        if SINGLETON_IF_NO_EDGES:
            communities = [{n} for n in nodes]
        else:
            communities = [set(nodes)]
    else:
        if method == "greedy_modularity":
            communities = list(nx.algorithms.community.greedy_modularity_communities(G, weight="weight"))
            communities = [set(c) for c in communities]
        else:
            raise ValueError(f"Unknown community method: {method}")

    # Sort modules by size descending, then name
    communities = sorted(communities, key=lambda c: (-len(c), sorted(list(c))[0] if c else ""))

    node_to_module = {}
    for i, comm in enumerate(communities, start=1):
        module_id = f"M{i}"
        for n in comm:
            node_to_module[n] = module_id

    return node_to_module, communities


# ============================================================
# 5. MODULE ASSIGNMENT AND SUMMARY
# ============================================================

def compute_module_assignment(cancer_code, group_name, G, node_to_module, dstage_df, node_metrics_df):
    """
    BP-level module assignment table.
    """
    rows = []

    dstage_map = {}
    if not dstage_df.empty and "term" in dstage_df.columns:
        tmp = dstage_df.set_index("term", drop=False)
        dstage_map = tmp.to_dict(orient="index")

    metric_sub = pd.DataFrame()
    if not node_metrics_df.empty and "group" in node_metrics_df.columns:
        metric_sub = node_metrics_df[node_metrics_df["group"].astype(str) == group_name].copy()

    metric_map = {}
    if not metric_sub.empty and "term" in metric_sub.columns:
        metric_map = metric_sub.set_index("term", drop=False).to_dict(orient="index")

    for node in G.nodes():
        module_id = node_to_module.get(node, "M_unassigned")
        drow = dstage_map.get(node, {})
        mrow = metric_map.get(node, {})

        rows.append({
            "cancer": cancer_code,
            "group": group_name,
            "term": node,
            "module_id": module_id,
            "degree": safe_float(mrow.get("degree", G.degree(node)), default=G.degree(node)),
            "weighted_degree": safe_float(mrow.get("weighted_degree", G.degree(node, weight="weight")), default=G.degree(node, weight="weight")),
            "betweenness": safe_float(mrow.get("betweenness", np.nan), default=np.nan),
            "D_stage": safe_float(drow.get("D_stage", np.nan)),
            "p_stage": safe_float(drow.get("p_stage", np.nan)),
            "delta_late_minus_early": safe_float(drow.get("delta_late_minus_early", np.nan)),
            "stage_trend": drow.get("stage_trend", None),
            "mu_early": safe_float(drow.get("mu_early", np.nan)),
            "mu_late": safe_float(drow.get("mu_late", np.nan)),
            "n_early": safe_float(drow.get("n_early", np.nan)),
            "n_late": safe_float(drow.get("n_late", np.nan)),
        })

    out = pd.DataFrame(rows)

    if not out.empty:
        out = out.sort_values(
            ["group", "module_id", "degree", "weighted_degree", "D_stage"],
            ascending=[True, True, False, False, False]
        )

    return out


def module_internal_edge_stats(G, nodes):
    """
    Compute internal graph stats for a module.
    """
    nodes = list(nodes)
    H = G.subgraph(nodes).copy()

    n_nodes = H.number_of_nodes()
    n_edges = H.number_of_edges()
    density = nx.density(H) if n_nodes > 1 else 0.0

    if n_edges > 0:
        weights = [d.get("weight", 1.0) for _, _, d in H.edges(data=True)]
        mean_weight = float(np.mean(weights))
        max_weight = float(np.max(weights))
    else:
        mean_weight = 0.0
        max_weight = 0.0

    return {
        "module_n_nodes": int(n_nodes),
        "module_n_edges": int(n_edges),
        "module_density": float(density),
        "module_mean_edge_weight": mean_weight,
        "module_max_edge_weight": max_weight,
    }


def compute_module_gene_overlap_stats(module_terms, gene_overlap_df):
    """
    Use pairwise BP gene overlap table to estimate redundancy inside a module.
    """
    terms = set(module_terms)

    if gene_overlap_df.empty or len(terms) <= 1:
        return {
            "mean_jaccard": np.nan,
            "max_jaccard": np.nan,
            "mean_overlap_coefficient": np.nan,
            "max_overlap_coefficient": np.nan,
            "mean_shared_genes": np.nan,
            "max_shared_genes": np.nan,
            "n_overlap_pairs": 0,
            "redundancy_warning": False
        }

    required = {"bp1", "bp2", "jaccard", "overlap_coefficient", "n_shared_genes"}
    if not required.issubset(set(gene_overlap_df.columns)):
        return {
            "mean_jaccard": np.nan,
            "max_jaccard": np.nan,
            "mean_overlap_coefficient": np.nan,
            "max_overlap_coefficient": np.nan,
            "mean_shared_genes": np.nan,
            "max_shared_genes": np.nan,
            "n_overlap_pairs": 0,
            "redundancy_warning": False
        }

    sub = gene_overlap_df[
        gene_overlap_df["bp1"].astype(str).isin(terms) &
        gene_overlap_df["bp2"].astype(str).isin(terms)
    ].copy()

    if sub.empty:
        return {
            "mean_jaccard": 0.0,
            "max_jaccard": 0.0,
            "mean_overlap_coefficient": 0.0,
            "max_overlap_coefficient": 0.0,
            "mean_shared_genes": 0.0,
            "max_shared_genes": 0.0,
            "n_overlap_pairs": 0,
            "redundancy_warning": False
        }

    mean_j = float(sub["jaccard"].mean())
    max_j = float(sub["jaccard"].max())
    mean_oc = float(sub["overlap_coefficient"].mean())
    max_oc = float(sub["overlap_coefficient"].max())
    mean_shared = float(sub["n_shared_genes"].mean())
    max_shared = float(sub["n_shared_genes"].max())

    warn = (
        mean_j >= MEAN_JACCARD_WARNING or
        max_j >= MAX_JACCARD_WARNING or
        mean_oc >= MEAN_OVERLAP_COEF_WARNING
    )

    return {
        "mean_jaccard": mean_j,
        "max_jaccard": max_j,
        "mean_overlap_coefficient": mean_oc,
        "max_overlap_coefficient": max_oc,
        "mean_shared_genes": mean_shared,
        "max_shared_genes": max_shared,
        "n_overlap_pairs": int(sub.shape[0]),
        "redundancy_warning": bool(warn)
    }


def infer_module_function_label(terms):
    """
    Lightweight keyword-based functional label.
    This is only an automatic draft label.
    """
    text = " ".join([str(t).upper() for t in terms])

    buckets = [
        ("ECM_EMT_INVASION", ["COLLAGEN", "EXTRACELLULAR", "MATRIX", "ECM", "ADHESION", "MIGRATION", "INVAS", "MOTILITY", "CARTILAGE"]),
        ("IMMUNE_INFLAMMATORY", ["INTERFERON", "CYTOKINE", "INFLAM", "T CELL", "B CELL", "LYMPH", "ANTIGEN", "IMMUNE", "LEUKOCYTE", "MACROPHAGE", "CHEMOKINE"]),
        ("PROLIFERATION_CELL_CYCLE", ["MITOTIC", "MITOSIS", "CELL CYCLE", "CHROMOSOME", "DNA REPLICATION", "E2F", "G2M", "SPINDLE"]),
        ("DNA_DAMAGE_REPAIR", ["DNA REPAIR", "DAMAGE", "P53", "RECOMBINATION", "DOUBLE STRAND", "NUCLEOTIDE EXCISION"]),
        ("METABOLISM", ["METABOL", "CATABOL", "BIOSYNTH", "GLYCOL", "LIPID", "FATTY", "AMINO ACID", "TRYPTOPHAN", "NAD", "SULFUR", "FOLIC"]),
        ("SIGNALING_TRANSPORT_MEMBRANE", ["SIGNALING", "TRANSPORT", "ENDOCYTOSIS", "VESICLE", "MEMBRANE", "RAFT", "RECEPTOR", "ION"]),
        ("TRANSLATION_RNA_PROCESSING", ["TRANSLATION", "MRNA", "RNA", "RIBOSOME", "SPLICING"]),
        ("STRESS_HYPOXIA_APOPTOSIS", ["STRESS", "HYPOXIA", "APOPTOSIS", "DEATH", "UV", "OXIDATIVE"]),
        ("DEVELOPMENT_DIFFERENTIATION", ["DEVELOPMENT", "DIFFERENTIATION", "MORPHOGENESIS", "ORGANOGENESIS"]),
    ]

    scores = {}
    for label, kws in buckets:
        scores[label] = sum(text.count(k) for k in kws)

    best_label, best_score = max(scores.items(), key=lambda x: x[1])
    if best_score == 0:
        return "MIXED_OR_UNLABELED"

    # If multiple labels tied/high, mark mixed
    sorted_scores = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    if len(sorted_scores) > 1 and sorted_scores[1][1] > 0 and sorted_scores[1][1] >= 0.7 * best_score:
        return f"MIXED_{best_label}_{sorted_scores[1][0]}"

    return best_label


def compute_module_summary(cancer_code, group_name, G, module_assignment_df, gene_overlap_df):
    """
    Module-level summary.
    """
    rows = []

    if module_assignment_df.empty:
        return pd.DataFrame()

    for module_id, sub in module_assignment_df.groupby("module_id"):
        terms = sub["term"].astype(str).tolist()
        hub_row = sub.sort_values(
            ["degree", "weighted_degree", "D_stage"],
            ascending=False
        ).iloc[0]

        edge_stats = module_internal_edge_stats(G, terms)
        overlap_stats = compute_module_gene_overlap_stats(terms, gene_overlap_df)

        trend_counts = sub["stage_trend"].value_counts(dropna=False).to_dict()
        n_late_high = int(trend_counts.get("late_high", 0))
        n_late_low = int(trend_counts.get("late_low", 0))
        n_terms = int(sub.shape[0])

        mean_delta = float(sub["delta_late_minus_early"].mean()) if "delta_late_minus_early" in sub.columns else np.nan
        mean_abs_delta = float(sub["delta_late_minus_early"].abs().mean()) if "delta_late_minus_early" in sub.columns else np.nan
        mean_D = float(sub["D_stage"].mean()) if "D_stage" in sub.columns else np.nan
        max_D = float(sub["D_stage"].max()) if "D_stage" in sub.columns else np.nan

        functional_label = infer_module_function_label(terms)

        rows.append({
            "cancer": cancer_code,
            "group": group_name,
            "module_id": module_id,
            "functional_label_auto": functional_label,
            "n_BP": n_terms,
            "hub_BP": hub_row["term"],
            "hub_degree": safe_float(hub_row.get("degree", np.nan)),
            "hub_weighted_degree": safe_float(hub_row.get("weighted_degree", np.nan)),
            "hub_D_stage": safe_float(hub_row.get("D_stage", np.nan)),
            "mean_D_stage": mean_D,
            "max_D_stage": max_D,
            "mean_delta_late_minus_early": mean_delta,
            "mean_abs_delta_late_minus_early": mean_abs_delta,
            "n_late_high": n_late_high,
            "n_late_low": n_late_low,
            "late_high_fraction": n_late_high / n_terms if n_terms > 0 else np.nan,
            "late_low_fraction": n_late_low / n_terms if n_terms > 0 else np.nan,
            "top_5_BP": " | ".join(sub.sort_values("D_stage", ascending=False)["term"].astype(str).head(5).tolist()),
            **edge_stats,
            **overlap_stats
        })

    out = pd.DataFrame(rows)

    if not out.empty:
        out = out.sort_values(
            ["group", "n_BP", "mean_D_stage", "module_density"],
            ascending=[True, False, False, False]
        )

    return out


# ============================================================
# 6. MODULE REWIRING EARLY VS LATE
# ============================================================

def compute_module_overlap_matrix(assign_early, assign_late, cancer_code):
    """
    Compare Early and Late module memberships.
    """
    if assign_early.empty or assign_late.empty:
        return pd.DataFrame(), pd.DataFrame()

    early_modules = {
        m: set(df["term"].astype(str))
        for m, df in assign_early.groupby("module_id")
    }
    late_modules = {
        m: set(df["term"].astype(str))
        for m, df in assign_late.groupby("module_id")
    }

    rows = []
    for em, es in early_modules.items():
        for lm, ls in late_modules.items():
            inter = es & ls
            union = es | ls
            rows.append({
                "cancer": cancer_code,
                "early_module": em,
                "late_module": lm,
                "n_early_BP": len(es),
                "n_late_BP": len(ls),
                "n_shared_BP": len(inter),
                "jaccard_BP": len(inter) / len(union) if len(union) > 0 else 0.0,
                "overlap_early_fraction": len(inter) / len(es) if len(es) > 0 else 0.0,
                "overlap_late_fraction": len(inter) / len(ls) if len(ls) > 0 else 0.0,
                "shared_BP": " | ".join(sorted(inter))
            })

    overlap_df = pd.DataFrame(rows)

    if not overlap_df.empty:
        overlap_df = overlap_df.sort_values(
            ["jaccard_BP", "n_shared_BP"],
            ascending=False
        )

    # Create module-level best match table
    rewiring_rows = []

    # Early -> best Late
    for em, es in early_modules.items():
        sub = overlap_df[overlap_df["early_module"] == em].copy()
        if sub.empty:
            continue
        best = sub.sort_values(["jaccard_BP", "n_shared_BP"], ascending=False).iloc[0]
        interpretation = classify_module_rewiring(
            jaccard=best["jaccard_BP"],
            overlap_from_source=best["overlap_early_fraction"],
            overlap_to_target=best["overlap_late_fraction"],
            source_size=best["n_early_BP"],
            target_size=best["n_late_BP"]
        )

        rewiring_rows.append({
            "cancer": cancer_code,
            "direction": "early_to_late",
            "source_module": em,
            "target_module": best["late_module"],
            "source_n_BP": int(best["n_early_BP"]),
            "target_n_BP": int(best["n_late_BP"]),
            "n_shared_BP": int(best["n_shared_BP"]),
            "jaccard_BP": float(best["jaccard_BP"]),
            "source_overlap_fraction": float(best["overlap_early_fraction"]),
            "target_overlap_fraction": float(best["overlap_late_fraction"]),
            "rewiring_class": interpretation,
            "shared_BP": best["shared_BP"]
        })

    # Late -> best Early
    for lm, ls in late_modules.items():
        sub = overlap_df[overlap_df["late_module"] == lm].copy()
        if sub.empty:
            continue
        best = sub.sort_values(["jaccard_BP", "n_shared_BP"], ascending=False).iloc[0]
        interpretation = classify_module_rewiring(
            jaccard=best["jaccard_BP"],
            overlap_from_source=best["overlap_late_fraction"],
            overlap_to_target=best["overlap_early_fraction"],
            source_size=best["n_late_BP"],
            target_size=best["n_early_BP"]
        )

        rewiring_rows.append({
            "cancer": cancer_code,
            "direction": "late_to_early",
            "source_module": lm,
            "target_module": best["early_module"],
            "source_n_BP": int(best["n_late_BP"]),
            "target_n_BP": int(best["n_early_BP"]),
            "n_shared_BP": int(best["n_shared_BP"]),
            "jaccard_BP": float(best["jaccard_BP"]),
            "source_overlap_fraction": float(best["overlap_late_fraction"]),
            "target_overlap_fraction": float(best["overlap_early_fraction"]),
            "rewiring_class": interpretation,
            "shared_BP": best["shared_BP"]
        })

    rewiring_df = pd.DataFrame(rewiring_rows)

    if not rewiring_df.empty:
        rewiring_df = rewiring_df.sort_values(
            ["direction", "jaccard_BP", "n_shared_BP"],
            ascending=[True, False, False]
        )

    return overlap_df, rewiring_df


def classify_module_rewiring(jaccard, overlap_from_source, overlap_to_target, source_size, target_size):
    """
    Heuristic labels.
    """
    if jaccard >= 0.70:
        return "module_preserved"
    if overlap_from_source >= 0.70 and overlap_to_target < 0.50:
        return "source_absorbed_into_larger_target"
    if overlap_from_source < 0.50 and overlap_to_target >= 0.70:
        return "target_is_fragment_of_source"
    if jaccard >= 0.35:
        return "partially_preserved"
    if overlap_from_source >= 0.40 or overlap_to_target >= 0.40:
        return "weakly_related"
    return "rewired_or_distinct"


def summarize_rewiring(cancer_code, rewiring_df, module_summary_df, net_summary_df):
    """
    Compact per-cancer summary.
    """
    out = {
        "cancer": cancer_code,
        "n_rewiring_pairs": int(rewiring_df.shape[0]) if not rewiring_df.empty else 0,
    }

    if not rewiring_df.empty:
        class_counts = rewiring_df["rewiring_class"].value_counts().to_dict()
        for k, v in class_counts.items():
            out[f"rewiring_class_count__{k}"] = int(v)

        early_to_late = rewiring_df[rewiring_df["direction"] == "early_to_late"]
        if not early_to_late.empty:
            out["mean_best_jaccard_early_to_late"] = float(early_to_late["jaccard_BP"].mean())
            out["max_best_jaccard_early_to_late"] = float(early_to_late["jaccard_BP"].max())

    if not module_summary_df.empty:
        for g in NETWORK_GROUPS:
            sub = module_summary_df[module_summary_df["group"] == g]
            out[f"{g}_n_modules"] = int(sub.shape[0])
            out[f"{g}_mean_module_size"] = float(sub["n_BP"].mean()) if not sub.empty else np.nan
            out[f"{g}_max_module_size"] = int(sub["n_BP"].max()) if not sub.empty else 0
            out[f"{g}_mean_module_density"] = float(sub["module_density"].mean()) if not sub.empty else np.nan
            out[f"{g}_redundancy_warning_modules"] = int(sub["redundancy_warning"].sum()) if "redundancy_warning" in sub.columns and not sub.empty else 0

    if not net_summary_df.empty and "group" in net_summary_df.columns:
        for _, r in net_summary_df.iterrows():
            g = str(r["group"])
            out[f"{g}_network_edges"] = safe_float(r.get("n_edges", np.nan))
            out[f"{g}_network_density"] = safe_float(r.get("density", np.nan))
            out[f"{g}_largest_component_size"] = safe_float(r.get("largest_component_size", np.nan))

        try:
            early_d = float(net_summary_df.loc[net_summary_df["group"] == EARLY_GROUP, "density"].iloc[0])
            late_d = float(net_summary_df.loc[net_summary_df["group"] == LATE_GROUP, "density"].iloc[0])
            out["late_minus_early_network_density"] = late_d - early_d
            if late_d - early_d > 0.05:
                out["network_reorganization_regime"] = "late_condensation"
            elif late_d - early_d < -0.05:
                out["network_reorganization_regime"] = "late_loosening"
            else:
                out["network_reorganization_regime"] = "density_stable"
        except Exception:
            out["late_minus_early_network_density"] = np.nan
            out["network_reorganization_regime"] = "unknown"

    return out


# ============================================================
# 7. FIGURES
# ============================================================

def plot_module_graph(G, assignment_df, cancer_code, group_name, out_path):
    """
    Network colored by module.
    Uses matplotlib default color cycle.
    """
    if G.number_of_nodes() == 0:
        return

    module_map = {}
    if not assignment_df.empty:
        module_map = assignment_df.set_index("term")["module_id"].to_dict()

    modules = sorted(set(module_map.get(n, "M?") for n in G.nodes()))
    mod_to_idx = {m: i for i, m in enumerate(modules)}
    node_colors = [mod_to_idx.get(module_map.get(n, "M?"), 0) for n in G.nodes()]

    degrees = dict(G.degree())
    node_sizes = [100 + 40 * degrees.get(n, 0) for n in G.nodes()]

    if G.number_of_edges() > 0:
        weights = [G[u][v].get("weight", 0.5) for u, v in G.edges()]
        widths = [0.5 + 2.0 * w for w in weights]
    else:
        widths = []

    plt.figure(figsize=(11, 9))
    pos = nx.spring_layout(G, seed=3, k=0.9)

    nx.draw_networkx_nodes(
        G,
        pos,
        node_size=node_sizes,
        node_color=node_colors,
        alpha=0.85,
        cmap=plt.cm.tab20
    )

    if G.number_of_edges() > 0:
        nx.draw_networkx_edges(
            G,
            pos,
            width=widths,
            alpha=0.35
        )

    nx.draw_networkx_labels(
        G,
        pos,
        labels={n: shorten_label(n) for n in G.nodes()},
        font_size=7
    )

    plt.title(f"{cancer_code}: {group_name} BP modules")
    plt.axis("off")
    plt.tight_layout()
    plt.savefig(out_path, dpi=300)
    plt.close()


def plot_module_size_bar(module_summary_df, cancer_code, out_path):
    if module_summary_df.empty:
        return

    plot_df = module_summary_df.copy()
    plot_df["module_label"] = plot_df["group"].astype(str) + ":" + plot_df["module_id"].astype(str)

    plt.figure(figsize=(12, 6))
    x = np.arange(plot_df.shape[0])
    plt.bar(x, plot_df["n_BP"].values)
    plt.xticks(x, plot_df["module_label"].tolist(), rotation=90, fontsize=7)
    plt.ylabel("Number of BP in module")
    plt.title(f"{cancer_code}: module sizes")
    plt.tight_layout()
    plt.savefig(out_path, dpi=300)
    plt.close()


def plot_overlap_heatmap(overlap_df, cancer_code, out_path):
    if overlap_df.empty:
        return

    early_modules = sorted(overlap_df["early_module"].unique())
    late_modules = sorted(overlap_df["late_module"].unique())

    mat = pd.DataFrame(0.0, index=early_modules, columns=late_modules)

    for _, r in overlap_df.iterrows():
        mat.loc[r["early_module"], r["late_module"]] = r["jaccard_BP"]

    plt.figure(figsize=(max(6, len(late_modules) * 0.8), max(5, len(early_modules) * 0.8)))
    plt.imshow(mat.values, aspect="auto", interpolation="nearest")
    plt.colorbar(label="BP Jaccard overlap")

    plt.xticks(range(len(late_modules)), late_modules, rotation=45, ha="right")
    plt.yticks(range(len(early_modules)), early_modules)

    plt.xlabel("Late modules")
    plt.ylabel("Early modules")
    plt.title(f"{cancer_code}: Early vs Late module overlap")

    plt.tight_layout()
    plt.savefig(out_path, dpi=300)
    plt.close()


# ============================================================
# 8. PER-CANCER PIPELINE
# ============================================================

def run_module_rewiring_one_cancer(cancer_dir):
    cancer_dir = Path(cancer_dir)
    data = load_v3_cancer_outputs(cancer_dir)
    cancer_code = data["cancer_code"]

    print("\n" + "=" * 100)
    print(f"[Cancer] {cancer_code}")
    print(f"[Input dir] {cancer_dir}")

    dstage = data["dstage"]
    selected = data["selected"]
    edges = data["edges"]
    node_metrics = data["node_metrics"]
    net_summary = data["net_summary"]
    gene_overlap = data["gene_overlap"]

    if selected.empty:
        print("[Skip] selected BP file empty.")
        return None

    if "term" not in selected.columns:
        print("[Skip] selected BP file has no term column.")
        return None

    selected_terms = selected["term"].dropna().astype(str).tolist()

    if len(selected_terms) == 0:
        print("[Skip] no selected BP terms.")
        return None

    cancer_out = OUT_DIR / cancer_code
    cancer_out.mkdir(parents=True, exist_ok=True)

    all_assignments = []
    all_module_summaries = []

    graph_by_group = {}
    assignment_by_group = {}

    for group_name in NETWORK_GROUPS:
        G = build_graph_for_group(edges, selected_terms, group_name)
        graph_by_group[group_name] = G

        node_to_module, communities = detect_communities(G, method=COMMUNITY_METHOD)

        assignment_df = compute_module_assignment(
            cancer_code=cancer_code,
            group_name=group_name,
            G=G,
            node_to_module=node_to_module,
            dstage_df=dstage,
            node_metrics_df=node_metrics
        )

        assignment_by_group[group_name] = assignment_df
        all_assignments.append(assignment_df)

        module_summary_df = compute_module_summary(
            cancer_code=cancer_code,
            group_name=group_name,
            G=G,
            module_assignment_df=assignment_df,
            gene_overlap_df=gene_overlap
        )

        all_module_summaries.append(module_summary_df)

        print(f"[{group_name}] nodes={G.number_of_nodes()} edges={G.number_of_edges()} modules={module_summary_df.shape[0]}")

        if MAKE_FIGURES:
            plot_module_graph(
                G,
                assignment_df,
                cancer_code,
                group_name,
                cancer_out / f"{cancer_code}_module_graph_{group_name}.png"
            )

    assignment_all = pd.concat(all_assignments, ignore_index=True) if all_assignments else pd.DataFrame()
    module_summary_all = pd.concat(all_module_summaries, ignore_index=True) if all_module_summaries else pd.DataFrame()

    assignment_all.to_csv(cancer_out / f"{cancer_code}_module_assignment.csv", index=False)
    module_summary_all.to_csv(cancer_out / f"{cancer_code}_module_summary.csv", index=False)

    # Early vs Late module rewiring
    assign_early = assignment_by_group.get(EARLY_GROUP, pd.DataFrame())
    assign_late = assignment_by_group.get(LATE_GROUP, pd.DataFrame())

    overlap_df, rewiring_df = compute_module_overlap_matrix(assign_early, assign_late, cancer_code)

    overlap_df.to_csv(cancer_out / f"{cancer_code}_module_overlap_matrix_early_vs_late.csv", index=False)
    rewiring_df.to_csv(cancer_out / f"{cancer_code}_module_rewiring_early_vs_late.csv", index=False)

    if MAKE_FIGURES:
        plot_module_size_bar(
            module_summary_all,
            cancer_code,
            cancer_out / f"{cancer_code}_module_sizes.png"
        )
        plot_overlap_heatmap(
            overlap_df,
            cancer_code,
            cancer_out / f"{cancer_code}_module_overlap_heatmap_early_vs_late.png"
        )

    summary = summarize_rewiring(
        cancer_code=cancer_code,
        rewiring_df=rewiring_df,
        module_summary_df=module_summary_all,
        net_summary_df=net_summary
    )

    with open(cancer_out / f"{cancer_code}_module_rewiring_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print("[Summary]")
    for k, v in summary.items():
        print(f"  {k}: {v}")

    return {
        "summary": summary,
        "assignment": assignment_all,
        "module_summary": module_summary_all,
        "rewiring": rewiring_df,
        "overlap": overlap_df,
    }


# ============================================================
# 9. MAIN
# ============================================================

def main():
    print("=" * 100)
    print("MOATTERS Stage BP Module Rewiring V1")
    print("=" * 100)
    print("Input:", INPUT_DIR)
    print("Output:", OUT_DIR)

    if not INPUT_DIR.exists():
        raise FileNotFoundError(f"Input directory not found: {INPUT_DIR}")

    cancer_dirs = find_v3_cancer_dirs(INPUT_DIR)

    print(f"[Found cancer dirs] n={len(cancer_dirs)}")
    for d in cancer_dirs:
        print(" -", d.name)

    all_summaries = []
    all_assignments = []
    all_module_summaries = []
    all_rewiring = []

    for cancer_dir in cancer_dirs:
        try:
            res = run_module_rewiring_one_cancer(cancer_dir)

            if res is None:
                continue

            all_summaries.append(res["summary"])

            if not res["assignment"].empty:
                all_assignments.append(res["assignment"])

            if not res["module_summary"].empty:
                all_module_summaries.append(res["module_summary"])

            if not res["rewiring"].empty:
                all_rewiring.append(res["rewiring"])

        except Exception as e:
            print(f"[ERROR] {cancer_dir.name}: {repr(e)}")
            import traceback
            traceback.print_exc()

    # Save all-cancer outputs
    if all_summaries:
        summary_df = pd.DataFrame(all_summaries)
        summary_df.to_csv(OUT_DIR / "MOATTERS_module_rewiring_all_cancer_summary.csv", index=False)
        print("\n[DONE] all-cancer summary saved.")
        print(summary_df.to_string(index=False))
    else:
        print("[DONE] no successful cancer summaries.")

    if all_assignments:
        pd.concat(all_assignments, ignore_index=True).to_csv(
            OUT_DIR / "MOATTERS_module_assignment_all_cancers.csv",
            index=False
        )

    if all_module_summaries:
        pd.concat(all_module_summaries, ignore_index=True).to_csv(
            OUT_DIR / "MOATTERS_module_summary_all_cancers.csv",
            index=False
        )

    if all_rewiring:
        pd.concat(all_rewiring, ignore_index=True).to_csv(
            OUT_DIR / "MOATTERS_module_rewiring_pairs_all_cancers.csv",
            index=False
        )

    print(f"\nOutput folder:\n{OUT_DIR}")


if __name__ == "__main__":
    main()
